modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/noeppi-noeppi/bongo/issues"
license="Apache-2.0"

[[mods]]
modId="bongo"
version="${file.jarVersion}"
displayName="Bongo"
displayURL="https://www.curseforge.com/minecraft/mc-mods/bongo"
authors="noeppi_noeppi, Contributors: MelanX, LordGrimmauld"
description='''
It's a bingo mod.
'''

[[dependencies.bongo]]
    modId="forge"
    mandatory=true
    versionRange="[34.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bongo]]
    modId="libx"
    mandatory=true
    versionRange="[1.16.3-1.0.11,)"
    ordering="NONE"
    side="BOTH"