name: 'Optimize Images ğŸ“–'
on: push

jobs:
  deploy:
    if: startsWith(github.repository, 'noeppi-noeppi/') # don't run this in forks
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout ğŸ›ï¸'
        uses: 'actions/checkout@v2'
        with:
          persist-credentials: false
          
      - name: 'Install dependencies ğŸ–¥'
        run: 'sudo apt-get install optipng'

      - name: 'Optimize Images ğŸ”§'
        run: |
          find . -name "*.png" -exec optipng -o7 {} \;

      - name: 'Install SSH Client ğŸ”‘'
        uses: 'webfactory/ssh-agent@v0.4.1'
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: 'Push ğŸš€'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin git@github.com:${{ github.repository }}.git
          
          git add -A
          git diff-index --quiet HEAD || git commit -m 'Optimized Images'
          git push